# Generated by Django 4.2.4 on 2024-03-22 11:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ETL', '0003_connections_psk_uid_jobs_psk_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connections',
            name='psk_uid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='psk_uid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='service_timer',
            name='psk_uid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True),
        ),
    ]
