"""latest

Revision ID: ef510772fe26
Revises: 
Create Date: 2025-02-15 16:56:13.539870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef510772fe26'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_auth_token_generator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('psk_uid', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('document_url', sa.String(), nullable=True),
    sa.Column('db_connection', sa.Integer(), nullable=True),
    sa.Column('db_connection_name', sa.String(), nullable=True),
    sa.Column('api_name', sa.String(), nullable=True),
    sa.Column('api_type', sa.String(), nullable=True),
    sa.Column('api_method', sa.String(), nullable=True),
    sa.Column('api_property', sa.Text(), nullable=True),
    sa.Column('api_header', sa.Text(), nullable=True),
    sa.Column('api_header_property', sa.Text(), nullable=True),
    sa.Column('api_header_requests', sa.Text(), nullable=True),
    sa.Column('token_type', sa.String(), nullable=True),
    sa.Column('expiry_period', sa.String(), nullable=True),
    sa.Column('expiry_datetime', sa.DateTime(), nullable=True),
    sa.Column('expiry_duration', sa.Integer(), nullable=True),
    sa.Column('expiry_rules', sa.Text(), nullable=True),
    sa.Column('expiry_property', sa.Text(), nullable=True),
    sa.Column('secret_key', sa.String(), nullable=True),
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('api_source', sa.String(), nullable=True),
    sa.Column('secret_key_start_datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_auth_token_generator_id'), 'api_auth_token_generator', ['id'], unique=False)
    op.create_table('api_connection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('psk_uid', sa.String(), nullable=True),
    sa.Column('db_engine', sa.String(), nullable=True),
    sa.Column('db_user', sa.String(), nullable=True),
    sa.Column('db_password', sa.String(), nullable=True),
    sa.Column('db_host', sa.String(), nullable=True),
    sa.Column('db_port', sa.String(), nullable=True),
    sa.Column('db_name', sa.String(), nullable=True),
    sa.Column('db_connection', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_connection_id'), 'api_connection', ['id'], unique=False)
    op.create_table('api_data_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_data_table_id'), 'api_data_table', ['id'], unique=False)
    op.create_table('api_schema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('psk_uid', sa.String(), nullable=True),
    sa.Column('api_connection_id', sa.Integer(), nullable=True),
    sa.Column('api_schemas', sa.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_schema_id'), 'api_schema', ['id'], unique=False)
    op.create_table('api_sql',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('psk_uid', sa.String(), nullable=True),
    sa.Column('api_name', sa.String(), nullable=True),
    sa.Column('api_type', sa.String(), nullable=True),
    sa.Column('api_method', sa.String(), nullable=True),
    sa.Column('db_connection', sa.Integer(), nullable=True),
    sa.Column('db_connection_name', sa.String(), nullable=True),
    sa.Column('api_schema', sa.String(), nullable=True),
    sa.Column('sql_text', sa.Text(), nullable=True),
    sa.Column('api_header_requests', sa.Text(), nullable=True),
    sa.Column('api_header', sa.Text(), nullable=True),
    sa.Column('api_header_property', sa.Text(), nullable=True),
    sa.Column('document_url', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('api_property', sa.Text(), nullable=True),
    sa.Column('api_source', sa.String(), nullable=True),
    sa.Column('api_trace', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_sql_id'), 'api_sql', ['id'], unique=False)
    op.create_table('api_sys_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_sys_config_id'), 'api_sys_config', ['id'], unique=True)
    op.create_table('api_auth_token_generator_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('log', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['api_auth_token_generator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_auth_token_generator_logs_id'), 'api_auth_token_generator_logs', ['id'], unique=False)
    op.create_table('api_auth_token_generator_migrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('psk_uid', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('document_url', sa.String(), nullable=True),
    sa.Column('db_connection', sa.Integer(), nullable=True),
    sa.Column('db_connection_name', sa.String(), nullable=True),
    sa.Column('api_name', sa.String(), nullable=True),
    sa.Column('api_type', sa.String(), nullable=True),
    sa.Column('api_method', sa.String(), nullable=True),
    sa.Column('api_property', sa.Text(), nullable=True),
    sa.Column('api_header', sa.Text(), nullable=True),
    sa.Column('api_header_property', sa.Text(), nullable=True),
    sa.Column('api_header_requests', sa.Text(), nullable=True),
    sa.Column('token_type', sa.String(), nullable=True),
    sa.Column('expiry_period', sa.String(), nullable=True),
    sa.Column('expiry_datetime', sa.DateTime(), nullable=True),
    sa.Column('expiry_duration', sa.Integer(), nullable=True),
    sa.Column('expiry_rules', sa.Text(), nullable=True),
    sa.Column('expiry_property', sa.Text(), nullable=True),
    sa.Column('secret_key', sa.String(), nullable=True),
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('api_source', sa.String(), nullable=True),
    sa.Column('secret_key_start_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['api_auth_token_generator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_auth_token_generator_migrations_id'), 'api_auth_token_generator_migrations', ['id'], unique=False)
    op.create_table('api_cms_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('psk_uid', sa.String(), nullable=True),
    sa.Column('api_name', sa.String(), nullable=True),
    sa.Column('api_type', sa.String(), nullable=True),
    sa.Column('api_method', sa.String(), nullable=True),
    sa.Column('api_source', sa.String(), nullable=True),
    sa.Column('db_connection', sa.Integer(), nullable=True),
    sa.Column('db_connection_name', sa.String(), nullable=True),
    sa.Column('api_property', sa.Text(), nullable=True),
    sa.Column('api_code_name', sa.Text(), nullable=True),
    sa.Column('api_code_file', sa.LargeBinary(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('api_header', sa.Text(), nullable=True),
    sa.Column('api_header_property', sa.Text(), nullable=True),
    sa.Column('api_header_requests', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['db_connection'], ['api_connection.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_name'),
    sa.UniqueConstraint('uid')
    )
    op.create_index(op.f('ix_api_cms_page_id'), 'api_cms_page', ['id'], unique=False)
    op.create_table('api_core',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('api_name', sa.String(), nullable=True),
    sa.Column('psk_uid', sa.String(), nullable=True),
    sa.Column('api_type', sa.String(), nullable=True),
    sa.Column('api_method', sa.String(), nullable=True),
    sa.Column('api_source', sa.String(), nullable=True),
    sa.Column('db_connection', sa.Integer(), nullable=True),
    sa.Column('db_connection_name', sa.String(), nullable=True),
    sa.Column('api_header_requests', sa.Text(), nullable=True),
    sa.Column('document_url', sa.String(), nullable=True),
    sa.Column('api_property', sa.Text(), nullable=True),
    sa.Column('api_code_name', sa.Text(), nullable=True),
    sa.Column('api_code_file', sa.LargeBinary(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('api_header', sa.Text(), nullable=True),
    sa.Column('api_header_property', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['db_connection'], ['api_connection.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_name'),
    sa.UniqueConstraint('uid')
    )
    op.create_index(op.f('ix_api_core_id'), 'api_core', ['id'], unique=False)
    op.create_table('api_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('table_details', sa.Text(), nullable=True),
    sa.Column('api_name', sa.String(), nullable=True),
    sa.Column('psk_uid', sa.String(), nullable=True),
    sa.Column('api_type', sa.String(), nullable=True),
    sa.Column('api_method', sa.String(), nullable=True),
    sa.Column('api_source', sa.String(), nullable=True),
    sa.Column('db_connection', sa.Integer(), nullable=True),
    sa.Column('db_connection_name', sa.String(), nullable=True),
    sa.Column('python_code', sa.Text(), nullable=True),
    sa.Column('python_file', sa.LargeBinary(), nullable=True),
    sa.Column('code_name', sa.Text(), nullable=True),
    sa.Column('document_url', sa.String(), nullable=True),
    sa.Column('api_property', sa.Text(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['db_connection'], ['api_connection.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_name'),
    sa.UniqueConstraint('uid')
    )
    op.create_index(op.f('ix_api_meta_id'), 'api_meta', ['id'], unique=False)
    op.create_table('api_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(), nullable=True),
    sa.Column('table_name_public', sa.String(), nullable=True),
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('psk_uid', sa.String(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('relations', sa.String(), nullable=True),
    sa.Column('db_connection', sa.Integer(), nullable=True),
    sa.Column('db_connection_name', sa.String(), nullable=True),
    sa.Column('readonly', sa.Boolean(), nullable=True),
    sa.Column('document_url', sa.String(), nullable=True),
    sa.Column('has_media', sa.Boolean(), nullable=True),
    sa.Column('has_posts', sa.Boolean(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['db_connection'], ['api_connection.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_name'),
    sa.UniqueConstraint('uid')
    )
    op.create_index(op.f('ix_api_models_id'), 'api_models', ['id'], unique=False)
    op.create_table('api_sql_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('psk_uid', sa.String(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('log', sa.Text(), nullable=True),
    sa.Column('api_action', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['api_sql.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_sql_logs_id'), 'api_sql_logs', ['id'], unique=False)
    op.create_table('api_sql_migrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('psk_uid', sa.String(), nullable=True),
    sa.Column('api_name', sa.String(), nullable=True),
    sa.Column('api_type', sa.String(), nullable=True),
    sa.Column('api_method', sa.String(), nullable=True),
    sa.Column('db_connection', sa.Integer(), nullable=True),
    sa.Column('db_connection_name', sa.String(), nullable=True),
    sa.Column('api_schema', sa.String(), nullable=True),
    sa.Column('sql_text', sa.Text(), nullable=True),
    sa.Column('api_header_requests', sa.Text(), nullable=True),
    sa.Column('api_header', sa.Text(), nullable=True),
    sa.Column('api_header_property', sa.Text(), nullable=True),
    sa.Column('document_url', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('api_property', sa.Text(), nullable=True),
    sa.Column('api_source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['api_sql.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_sql_migrations_id'), 'api_sql_migrations', ['id'], unique=False)
    op.create_table('api_sql_trace',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('psk_uid', sa.String(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('api_request_payload', sa.Text(), nullable=True),
    sa.Column('api_response_payload', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['api_sql.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_sql_trace_id'), 'api_sql_trace', ['id'], unique=False)
    op.create_table('api_cms_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('psk_uid', sa.String(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('log', sa.Text(), nullable=True),
    sa.Column('api_action', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['api_cms_page.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_cms_logs_id'), 'api_cms_logs', ['id'], unique=False)
    op.create_table('api_cms_page_migrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('psk_uid', sa.String(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('api_name', sa.String(), nullable=True),
    sa.Column('api_type', sa.String(), nullable=True),
    sa.Column('api_method', sa.String(), nullable=True),
    sa.Column('api_source', sa.String(), nullable=True),
    sa.Column('db_connection', sa.Integer(), nullable=True),
    sa.Column('db_connection_name', sa.String(), nullable=True),
    sa.Column('api_property', sa.Text(), nullable=True),
    sa.Column('api_code_name', sa.Text(), nullable=True),
    sa.Column('api_code_file', sa.LargeBinary(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('api_header', sa.Text(), nullable=True),
    sa.Column('api_header_property', sa.Text(), nullable=True),
    sa.Column('api_header_requests', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['db_connection'], ['api_connection.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['api_cms_page.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_cms_page_migrations_id'), 'api_cms_page_migrations', ['id'], unique=False)
    op.create_table('api_core_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('psk_uid', sa.String(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('log', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['api_core.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_core_logs_id'), 'api_core_logs', ['id'], unique=False)
    op.create_table('api_core_migrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('psk_uid', sa.String(), nullable=True),
    sa.Column('api_name', sa.String(), nullable=True),
    sa.Column('api_type', sa.String(), nullable=True),
    sa.Column('api_method', sa.String(), nullable=True),
    sa.Column('api_source', sa.String(), nullable=True),
    sa.Column('db_connection', sa.Integer(), nullable=True),
    sa.Column('db_connection_name', sa.String(), nullable=True),
    sa.Column('api_header_requests', sa.Text(), nullable=True),
    sa.Column('document_url', sa.String(), nullable=True),
    sa.Column('api_property', sa.Text(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('api_code_name', sa.Text(), nullable=True),
    sa.Column('api_code_file', sa.LargeBinary(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('api_header', sa.Text(), nullable=True),
    sa.Column('api_header_property', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['db_connection'], ['api_connection.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['api_core.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_core_migrations_id'), 'api_core_migrations', ['id'], unique=False)
    op.create_table('api_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=True),
    sa.Column('field_name_public', sa.String(), nullable=True),
    sa.Column('psk_uid', sa.String(), nullable=True),
    sa.Column('field_data_type', sa.String(), nullable=True),
    sa.Column('related_to', sa.String(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('field_property', sa.Text(), nullable=True),
    sa.Column('field_rule', sa.Text(), nullable=True),
    sa.Column('field_select', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['api_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_fields_id'), 'api_fields', ['id'], unique=False)
    op.create_table('api_meta_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('psk_uid', sa.String(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('log', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['api_meta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_meta_logs_id'), 'api_meta_logs', ['id'], unique=False)
    op.create_table('api_meta_migrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('table_details', sa.Text(), nullable=True),
    sa.Column('api_name', sa.String(), nullable=True),
    sa.Column('psk_uid', sa.String(), nullable=True),
    sa.Column('api_type', sa.String(), nullable=True),
    sa.Column('api_method', sa.String(), nullable=True),
    sa.Column('api_source', sa.String(), nullable=True),
    sa.Column('db_connection', sa.Integer(), nullable=True),
    sa.Column('db_connection_name', sa.String(), nullable=True),
    sa.Column('python_code', sa.Text(), nullable=True),
    sa.Column('code_name', sa.Text(), nullable=True),
    sa.Column('python_file', sa.LargeBinary(), nullable=True),
    sa.Column('document_url', sa.String(), nullable=True),
    sa.Column('api_property', sa.Text(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['db_connection'], ['api_connection.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['api_meta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_meta_migrations_id'), 'api_meta_migrations', ['id'], unique=False)
    op.create_table('api_models_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('log', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['api_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_models_logs_id'), 'api_models_logs', ['id'], unique=False)
    op.create_table('api_models_migrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(), nullable=True),
    sa.Column('table_name_public', sa.String(), nullable=True),
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('psk_uid', sa.String(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('relations', sa.String(), nullable=True),
    sa.Column('db_connection', sa.Integer(), nullable=True),
    sa.Column('db_connection_name', sa.String(), nullable=True),
    sa.Column('readonly', sa.Boolean(), nullable=True),
    sa.Column('document_url', sa.String(), nullable=True),
    sa.Column('has_media', sa.Boolean(), nullable=True),
    sa.Column('has_posts', sa.Boolean(), nullable=True),
    sa.Column('migration_name', sa.String(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('fields_list', sa.Text(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['db_connection'], ['api_connection.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['api_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_models_migrations_id'), 'api_models_migrations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_models_migrations_id'), table_name='api_models_migrations')
    op.drop_table('api_models_migrations')
    op.drop_index(op.f('ix_api_models_logs_id'), table_name='api_models_logs')
    op.drop_table('api_models_logs')
    op.drop_index(op.f('ix_api_meta_migrations_id'), table_name='api_meta_migrations')
    op.drop_table('api_meta_migrations')
    op.drop_index(op.f('ix_api_meta_logs_id'), table_name='api_meta_logs')
    op.drop_table('api_meta_logs')
    op.drop_index(op.f('ix_api_fields_id'), table_name='api_fields')
    op.drop_table('api_fields')
    op.drop_index(op.f('ix_api_core_migrations_id'), table_name='api_core_migrations')
    op.drop_table('api_core_migrations')
    op.drop_index(op.f('ix_api_core_logs_id'), table_name='api_core_logs')
    op.drop_table('api_core_logs')
    op.drop_index(op.f('ix_api_cms_page_migrations_id'), table_name='api_cms_page_migrations')
    op.drop_table('api_cms_page_migrations')
    op.drop_index(op.f('ix_api_cms_logs_id'), table_name='api_cms_logs')
    op.drop_table('api_cms_logs')
    op.drop_index(op.f('ix_api_sql_trace_id'), table_name='api_sql_trace')
    op.drop_table('api_sql_trace')
    op.drop_index(op.f('ix_api_sql_migrations_id'), table_name='api_sql_migrations')
    op.drop_table('api_sql_migrations')
    op.drop_index(op.f('ix_api_sql_logs_id'), table_name='api_sql_logs')
    op.drop_table('api_sql_logs')
    op.drop_index(op.f('ix_api_models_id'), table_name='api_models')
    op.drop_table('api_models')
    op.drop_index(op.f('ix_api_meta_id'), table_name='api_meta')
    op.drop_table('api_meta')
    op.drop_index(op.f('ix_api_core_id'), table_name='api_core')
    op.drop_table('api_core')
    op.drop_index(op.f('ix_api_cms_page_id'), table_name='api_cms_page')
    op.drop_table('api_cms_page')
    op.drop_index(op.f('ix_api_auth_token_generator_migrations_id'), table_name='api_auth_token_generator_migrations')
    op.drop_table('api_auth_token_generator_migrations')
    op.drop_index(op.f('ix_api_auth_token_generator_logs_id'), table_name='api_auth_token_generator_logs')
    op.drop_table('api_auth_token_generator_logs')
    op.drop_index(op.f('ix_api_sys_config_id'), table_name='api_sys_config')
    op.drop_table('api_sys_config')
    op.drop_index(op.f('ix_api_sql_id'), table_name='api_sql')
    op.drop_table('api_sql')
    op.drop_index(op.f('ix_api_schema_id'), table_name='api_schema')
    op.drop_table('api_schema')
    op.drop_index(op.f('ix_api_data_table_id'), table_name='api_data_table')
    op.drop_table('api_data_table')
    op.drop_index(op.f('ix_api_connection_id'), table_name='api_connection')
    op.drop_table('api_connection')
    op.drop_index(op.f('ix_api_auth_token_generator_id'), table_name='api_auth_token_generator')
    op.drop_table('api_auth_token_generator')
    # ### end Alembic commands ###
