# Generated by Django 5.0.4 on 2025-02-15 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiMeta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('original_id', models.IntegerField(blank=True, null=True)),
                ('uid', models.CharField(blank=True, max_length=1000, null=True)),
                ('table_details', models.TextField(blank=True, null=True)),
                ('api_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('psk_uid', models.CharField(blank=True, max_length=1000, null=True)),
                ('api_type', models.CharField(blank=True, max_length=1000, null=True)),
                ('api_method', models.CharField(blank=True, max_length=1000, null=True)),
                ('api_source', models.CharField(blank=True, max_length=1000, null=True)),
                ('db_connection', models.IntegerField(blank=True, null=True)),
                ('db_connection_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('code_name', models.TextField(blank=True, null=True)),
                ('python_file', models.TextField(blank=True, null=True)),
                ('document_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('api_property', models.TextField(blank=True, default='API_DEFAULT_PROPERTY', null=True)),
            ],
            options={
                'db_table': 'api_meta',
            },
        ),
        migrations.CreateModel(
            name='DBImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='db_imports/%d-%m-%Y/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MigrationList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('original_id', models.IntegerField(blank=True, null=True)),
                ('table_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('table_name_public', models.CharField(blank=True, max_length=1000, null=True)),
                ('uid', models.CharField(blank=True, max_length=1000, null=True)),
                ('psk_uid', models.CharField(blank=True, max_length=1000, null=True)),
                ('published', models.BooleanField(blank=True, default=False, null=True)),
                ('version', models.IntegerField(blank=True, default=0, null=True)),
                ('relations', models.CharField(blank=True, max_length=1000, null=True)),
                ('db_connection', models.IntegerField(blank=True, null=True)),
                ('db_connection_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('readonly', models.BooleanField(blank=True, default=False, null=True)),
                ('document_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('has_media', models.BooleanField(blank=True, default=False, null=True)),
                ('has_posts', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'db_table': 'api_models',
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('original_id', models.IntegerField(blank=True, null=True)),
                ('field_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('field_name_public', models.CharField(blank=True, max_length=1000, null=True)),
                ('psk_uid', models.CharField(blank=True, max_length=1000, null=True)),
                ('field_data_type', models.CharField(blank=True, max_length=1000, null=True)),
                ('related_to', models.CharField(blank=True, max_length=1000, null=True)),
                ('table_id', models.IntegerField(blank=True, null=True)),
                ('published', models.BooleanField(blank=True, default=False, null=True)),
                ('archived', models.BooleanField(blank=True, default=False, null=True)),
                ('field_property', models.TextField(blank=True, default='{}', null=True)),
                ('field_rule', models.TextField(blank=True, null=True)),
                ('field_select', models.TextField(blank=True, null=True)),
                ('dj_table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='core.table')),
            ],
            options={
                'db_table': 'api_fields',
            },
        ),
    ]
