# Generated by Django 5.0.6 on 2025-02-15 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPermissionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('access_role', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='StudioMenus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(blank=True, max_length=200, null=True)),
                ('menu_uid', models.CharField(max_length=200, unique=True)),
                ('menu_href', models.CharField(blank=True, max_length=200, null=True)),
                ('menu_ui_code', models.CharField(blank=True, max_length=200, null=True)),
                ('icon_class', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('menu_order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AppPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('group_name', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=200)),
                ('updated_by', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studio_menus', models.ManyToManyField(blank=True, to='user_master.studiomenus')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
