# Generated by Django 4.2.4 on 2024-03-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ETL', '0002_alter_jobs_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='connections',
            name='psk_uid',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='psk_uid',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='service_timer',
            name='psk_uid',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AlterModelTable(
            name='connections',
            table='etl_connections',
        ),
        migrations.AlterModelTable(
            name='jobs',
            table='etl_jobs',
        ),
        migrations.AlterModelTable(
            name='service_timer',
            table='etl_jobs_timer',
        ),
    ]
