# Generated by Django 4.2.4 on 2024-04-27 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ETL', '0004_alter_connections_psk_uid_alter_jobs_psk_uid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='source_api',
            new_name='core_api',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='project',
            new_name='project_group',
        ),
    ]
